services:
  synchronist: &synchronist
    image: siegy22/synchronist
    depends_on:
      - redis
      - postgres
    volumes:
      - /data:/data:z
      - /sync:/sync:z
      - synchronist_storage:/synchronist/storage
    environment:
      DATABASE_URL: postgresql://test:test@postgres/sync
      REDIS_URL: redis://redis:6379/1
      SYNCHRONIST_USERNAME: "siegy"
      SYNCHRONIST_PASSWORD: "bschorle"
      SECRET_KEY_BASE: "12314128917958128951892591518582"
    ports:
      - 80:3000
    restart: always
  synchronist-worker:
    <<: *synchronist
    command: bundle exec sidekiq
    ports: []
  redis:
    image: redis
    volumes:
      - redis_data:/data
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: sync
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  synchronist_storage:
  pg_data:
  redis_data:
