services:
  synchronist: &synchronist
    image: siegy22/synchronist
    depends_on:
      - redis
      - postgres
    volumes:
      - synchronist_storage:/synchronist/storage
<volumes>
    environment:
      DATABASE_URL: "postgresql://synchronist:<pg_password>@postgres/synchronist"
      REDIS_URL: redis://redis:6379/1
      SYNCHRONIST_USERNAME: "<username>"
      SYNCHRONIST_PASSWORD: "<password>"
      SECRET_KEY_BASE: "<secret_key>"
    ports:
      - "<port>:3000"
    restart: always
  synchronist-worker:
    <<: *synchronist
    command: bundle exec sidekiq
    ports: []
  redis:
    image: redis
    volumes:
      - redis_data:/data
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: synchronist
      POSTGRES_PASSWORD: "<pg_password>"
      POSTGRES_DB: synchronist
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  synchronist_storage:
  pg_data:
  redis_data:
